
![Logo](https://raw.githubusercontent.com/Machine-Learning-Basic/main/README_imgs/aifreeteam.png) 
<center>Welcome to the course《Python: from business analytics to Artificial Intelligence》by AI.FREE Team.</center>
<center>歡迎大家來到 AI.FREE Team 《Python 從商業分析到人工智慧》的第二堂課 - 機器學習(ML)基礎教學。 </center>
<br/>

<center>作者: Tom Wu (<a href="https://github.com/YenLinWu">Github</a>)</center>
<center>AI.FREE Team: <a href="https://aifreeblog.herokuapp.com/">https://aifreeblog.herokuapp.com/</a></center>
<br>




# 前言  
本篇文章將介紹 Python 最基礎的套件之一 <font color="#00dd00">**NumPy**</font>，透過學習 NumPy 可建立我們處理及分析資料的基本功。讀者們在閱讀本篇文章後，將具備下列有關 NumPy 的基本知識與能力：  
  1. NumPy 如何建立陣列( Array )   
  2. NumPy 如何建立特殊的陣列( Array ) 
  3. NumPy 如何進行陣列( Array )的四則運算：廣播( Broadcasting )機制  
  4. NumPy 如何進行矩陣( Matrix )的運算  
  5. NumPy 提供的數學函數





# <font color="#00dd00">**NumPy**</font> 是什麼？

NumPy 全名為 Numeric Python(或 Numerical Python)，是我們運用 Python 進行資料分析時，一個基本且重要的套件之一。NumPy 提供一維、多維陣列( Array )的操作，例如：排序、篩選元素等，同時也具備陣列、矩陣的數學與邏輯運算能力。NumPy 最主要的優勢，是它具備平行運算與處理資料的能力，當我們有非常龐大的資料要分析時，NumPy 能支援高效率的向量與矩陣數學運算。另外，其他有關資料科學的重要 Python 套件，例如：Pandas、SciPy、Scikit-learn 等，幾乎都是建立在 NumPy 的基礎上。因此，若我們能打好 NumPy 基礎，對於日後學習其他套件將會有很大的幫助！

# 匯入套件

In [1]:
from platform import python_version
import numpy as np
print( 'Python Version:', python_version() ) 
print( 'Numpy Version:', np.__version__ )

Python Version: 3.6.9
Numpy Version: 1.18.5


# <font color="#00dd00">**陣列( Array )**</font> 

<font color="#00dd00">陣列( Array )</font>是程式語言中基本的資料結構之一，儲存在陣列中的資料稱為元素( element )，NumPy 的陣列為一序列整數或浮點數所組成，ndarray( $n$-dimension array )為 NumPy 所提供的陣列型別，其中 $n$ 表示陣列的維度。NumPy 陣列與 Python [列表( List )](https://colab.research.google.com/github/AI-FREE-Team/Python-Basics/blob/master/documents/Lesson05%20List.ipynb)非常類似，兩者最主要的差別在於，NumPy 陣列中每個元素的資料型態是一致的( int 或 float )，Python 列表則可以儲存不同型態的資料。

## 建立 $n$( $\ge$ 1 ) 維陣列   

我們可透過 `array( )` 函數來建立 $n$( $\ge$ 1 )維的陣列。

(i) 建立一維陣列


In [2]:
A1 = np.array( [1,3,5,7] )

print( f'1-dimension Array A1: {A1}\n' )
print( f'Type of Element in A1: {A1.dtype}' )
print( f'Dimension of A1 = {A1.ndim}' )
print( f'Shape of A1 = {A1.shape}' )

1-dimension Array A1: [1 3 5 7]

Type of Element in A1: int64
Dimension of A1 = 1
Shape of A1 = (4,)


(ii) 建立二維陣列

In [3]:
A2 = np.array([ [1,3,5,7], [9,11,13,15], [17,19,21,23.5] ])

print( f'2-dimension Array A2: \n{A2}\n' )
print( f'Type of Element in A2: {A2.dtype}' )
print( f'Dimension of A2 = {A2.ndim}' )
print( f'Shape of A2 = {A2.shape}' )

2-dimension Array A2: 
[[ 1.   3.   5.   7. ]
 [ 9.  11.  13.  15. ]
 [17.  19.  21.  23.5]]

Type of Element in A2: float64
Dimension of A2 = 2
Shape of A2 = (3, 4)


## 建立特殊的陣列   

除了可用上述 `array( )` 函數來建立陣列之外，NumPy 還提供我們建立特殊陣列的多種函數，例如：`arange( )`、`linspace( )`、`zeros( )`、`ones( )`、`full( )`、`random( )`、`randint( )`、`randn( )`等，下列將介紹幾個建立特殊陣列的基本函數：

### [arange( )](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) : 建立一區間內的數值陣列

In [4]:
# 產生 [1,8) 中整數的一維陣列
A1 = np.arange( 1, 8 )

# 產生 [1,8) 之間的奇數一維陣列，且元素的資料型態設為浮點數(float)
A2 = np.arange( 1, 8, 2, dtype=float )

print( f'[1,8) 中整數的一維陣列：{A1}' ) 
print( f'[1,8) 中奇數的一維陣列：{A2}' )  

[1,8) 中整數的一維陣列：[1 2 3 4 5 6 7]
[1,8) 中奇數的一維陣列：[1. 3. 5. 7.]


### [linspace( )](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) : 建立一區間等分割子區間的端點數值陣列

In [5]:
# 產生 [ 1, 3 ] 中等分割 4 等分的數值點(1、1.5、2、2.5、3)陣列
L = np.linspace( 1, 3, 5)

print( f'4 等分 [1,3] 區間的子區間端點陣列：{L}' )

4 等分 [1,3] 區間的子區間端點陣列：[1.  1.5 2.  2.5 3. ]


### [zeros( )](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html) : 建立元素皆為 0 的陣列，資料型態預設為 float

In [6]:
# 產生元素皆為 0 的一維陣列(元素個數 = 3)
Z1 = np.zeros( 3 )

# 產生元素皆為 0 的二維陣列，且元素的資料型態設為整數(int)
Z2 = np.zeros( (3,4), dtype=int )

print( f'3 個元素 0 組成的一維陣列：{Z1}\n' ) 
print( f'元素 0 組成的 3x4 二維陣列：\n{Z2}' ) 

3 個元素 0 組成的一維陣列：[0. 0. 0.]

元素 0 組成的 3x4 二維陣列：
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### [ones( )](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html) : 建立元素皆為 1 的陣列，資料型態預設為 float

In [7]:
# 產生元素皆為 1 的一維陣列(元素個數 = 3)
O1 = np.ones( 3 )

# 產生元素皆為 1 的二維陣列，且元素的資料型態設為整數(int)
O2 = np.ones( (3,4), dtype=int )

print( f'3 個元素 1 組成的一維陣列：{O1}\n' ) 
print( f'元素 1 組成的 3x4 二維陣列：\n{O2}' ) 

3 個元素 1 組成的一維陣列：[1. 1. 1.]

元素 1 組成的 3x4 二維陣列：
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### [full( )](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.fill.html) : 建立指定元素的陣列

In [8]:
# 產生元素皆為 3 的一維陣列(元素個數 = 4)
F1 = np.full( 4, 3 )

# 產生元素皆為 5 的二維陣列，且元素的資料型態設為整數(int)
F2 = np.full( (3,4), 5 )

print( f'4 個元素 3 組成的一維陣列：{F1}\n' ) 
print( f'元素 5 組成的 3x4 二維陣列：\n{F2}' ) 

4 個元素 3 組成的一維陣列：[3 3 3 3]

元素 5 組成的 3x4 二維陣列：
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# <font color="#00dd00">**random**</font> 模組   

使用 NumPy 中的 random 模組，我們能用亂數來建立特殊的陣列，相關函數的說明如下：
   * [random( )](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html) : 產生 $[0.0,1.0)$ 之間的**浮點數**亂數     
   * [randint( a, b )](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html) : 產生 $[a,b)$ 之間的**整數**亂數   
   * [rand( )](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html) : 從 $[0,1)$ 均勻分配( Uniform Distribution )中隨機亂數產生樣本資料  
   * [randn( )](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html) : 從**標準常態分配( Standard Normal Distribution )**中隨機亂數產生樣本資料

In [9]:
# 產生 [0,1) 隨機亂數的一維陣列(元素個數 = 3)
R1 = np.random.random( 3 )

# 產生 [1,10) 中隨機亂數的一維陣列(元素個數 = 4)
R2 = np.random.randint( 1, 10, size=4 )

# 從 [0,1) 均勻分配隨機亂數產生一維陣列(元素個數 = 5)
R3 = np.random.rand( 5 )

# 從標準常態分配隨機亂數產生二維(2x3)陣列
R4 = np.random.randn( 2, 3 )

print( f'[0,1)中隨機亂數(浮點數)的一維陣列 R1 : \n{R1}\n' )
print( f'[1,10)中隨機亂數(整數)的一維陣列 R2 : \n{R2}\n' )
print( f'從均勻分配隨機亂數產生一維陣列 R3 : \n{R3}\n' )
print( f'從標準常態分配隨機亂數產生二維陣列 R4 : \n{R4}' )

[0,1)中隨機亂數(浮點數)的一維陣列 R1 : 
[0.79928324 0.86366557 0.57308085]

[1,10)中隨機亂數(整數)的一維陣列 R2 : 
[5 3 5 7]

從均勻分配隨機亂數產生一維陣列 R3 : 
[0.62240364 0.46024151 0.46955837 0.84202716 0.63289372]

從標準常態分配隨機亂數產生二維陣列 R4 : 
[[-0.0993551   0.12308492 -0.49859307]
 [-0.04556823  1.51473467  0.41582602]]


# 陣列的四則運算

當兩個 NumPy 陣列的**形狀( Shape )相同**時，則這兩個 NumPy 陣列能夠進行加、減、乘、除的四則運算。

In [10]:
V1 = np.array([1,3,5])
V2 = np.array([2,4,6])

# 陣列加法
A = V1 + V2
# 陣列減法
S = V1 - V2
# 陣列乘法
M = V1 * V2
# 陣列除法
D = V1 / V2

print( f'V1 = {V1}\nV2 = {V2}\n' )
print( f'V1 + V2 = {A}' ) 
print( f'V1 - V2 = {S}' ) 
print( f'V1 * V2 = {M}' ) 
print( f'V1 / V2 = {D}' ) 

V1 = [1 3 5]
V2 = [2 4 6]

V1 + V2 = [ 3  7 11]
V1 - V2 = [-1 -1 -1]
V1 * V2 = [ 2 12 30]
V1 / V2 = [0.5        0.75       0.83333333]


# <font color="#00dd00">**廣播( Broadcasting )**</font> 機制

更精確而言，<font color="#dddd00">兩個 NumPy 陣列要能進行四則運算的條件，為這兩個陣列的形狀( Shape )必須相容( Compatible )</font>，當遭遇形狀不相容的情況時，則會產生如下面範例的錯誤訊息：

In [11]:
V1 = np.array( [1,3,5,7] )
V2 = np.array([ [2,4], [6,8] ])
V1 * V2  # 陣列乘法

ValueError: ignored

NumPy 提供一個用來處理不同形狀的陣列進行四則運算的機制 － <font color="#00dd00">**廣播( Broadcasting )**</font>：<font color="#dddd00">當兩個陣列 V1、V2 的形狀不同，且 V1 的形狀規模較 V2 小，則規模較小的陣列 V1 會擴張成與較大陣列 V2 相容的形狀，再進行四則運算。</font>  
舉例如下： V1 為形狀 $(4,)$ 的一維陣列， V2 為形狀 $( 2, 4 )$ 的二維陣列，透過廣播機制，在進行 `V1*V2` 陣列乘法之前， V1 會自動擴張成 $[ [1,3,5,7], [1,3,5,7] ]$ 與 V2 相容的形狀。

In [12]:
V1 = np.array( [1,3,5,7] )
V2 = np.array( [ [2,4,6,8], [10,12,14,16] ] )

print( f'V1 = {V1}\nV2 = \n{V2}\n' )
print( f'Shape of V1 = {V1.shape}' )
print( f'Shape of V2 = {V2.shape}\n' )
print( f'V1 * V2 = \n{V1*V2}' ) 

V1 = [1 3 5 7]
V2 = 
[[ 2  4  6  8]
 [10 12 14 16]]

Shape of V1 = (4,)
Shape of V2 = (2, 4)

V1 * V2 = 
[[  2  12  30  56]
 [ 10  36  70 112]]


# 向量\矩陣的轉置及運算  

我們可使用 NumPy 一維陣列來表示向量( vector )、二維陣列來表示矩陣( matrix )，下列將介紹矩陣的轉置( Transposition )、加法( Addition )及乘法( Multiplication )運算：

### 矩陣轉置( Transposition )  

我們可使用 `transpose( )` 函數進行矩陣的轉置，下列為轉置一個 $2\times3$ 矩陣的數學表示法：  
$\mathbf{v}^\intercal$ = 
$ \Bigg(
 \left[
 \begin{matrix}
   v_{11} & v_{12} & v_{13} \\ v_{21} & v_{22} & v_{23} 
  \end{matrix}
  \right]
\Bigg)^\intercal $ =
$
 \left[
 \begin{matrix}
   v_{11} & v_{21} \\ v_{12} & v_{22} \\ v_{13} & v_{23}
  \end{matrix}
  \right]
$


In [13]:
V = np.array( [[1,2,3],[4,5,6]] )

# 矩陣轉置
V_T = np.transpose( V )

print( f'V = \n{V}\n' )
print( f'使用 transpose( ) 函數轉置 V = \n{V_T}\n' )

V = 
[[1 2 3]
 [4 5 6]]

使用 transpose( ) 函數轉置 V = 
[[1 4]
 [2 5]
 [3 6]]



### 矩陣加法( Matrix Addition )   

$ V_{2x3} \pm W_{2x3} $ =
$
 \left[
 \begin{matrix}
   v_{11} & v_{12} & v_{13} \\ v_{21} & v_{22} & v_{23} 
  \end{matrix}
  \right]
$ 
$\pm$ 
$
 \left[
 \begin{matrix}
   w_{11} & w_{12} & w_{13} \\ w_{21} & w_{22} & w_{23}
  \end{matrix}
  \right]
$ = 
$
 \left[
 \begin{matrix}
   v_{11}\pm w_{11} & v_{12}\pm w_{12} & v_{13}\pm w_{13} \\ v_{21}\pm w_{21} & v_{22}\pm w_{22} & v_{23}\pm w_{23}
  \end{matrix}
  \right]_{2x3}
$  

In [14]:
V = np.array( [[1,3,5],[7,9,11]] )
W = np.array( [[2,4,6],[8,10,12]] )

# 矩陣相加
P = V + W
# 矩陣相減
M = V - W

print( f'V = \n{V}\n' )
print( f'W = \n{W}\n' )
print( f'矩陣相加 V + W = \n{P}\n' )
print( f'矩陣相減 V - W = \n{M}' )

V = 
[[ 1  3  5]
 [ 7  9 11]]

W = 
[[ 2  4  6]
 [ 8 10 12]]

矩陣相加 V + W = 
[[ 3  7 11]
 [15 19 23]]

矩陣相減 V - W = 
[[-1 -1 -1]
 [-1 -1 -1]]


### 矩陣乘法( Matrix Multiplication )    

我們可以透過 `dot( )` 函數或 ` @ ` 進行矩陣的乘法，下列為 $2\times3$ 矩陣與 $3\times2$ 矩陣兩者的乘法運算方式：   

$ V_{2x3} \cdot W_{3X2} $ =
$
 \left[
 \begin{matrix}
   v_{11} & v_{12} & v_{13} \\ v_{21} & v_{22} & v_{23} 
  \end{matrix}
  \right]
$ 
$\cdot$ 
$
 \left[
 \begin{matrix}
   w_{11} & w_{12} \\ w_{21} & w_{22} \\ w_{31} & w_{32}
  \end{matrix}
  \right]
$ = 
$
 \left[
 \begin{matrix}
   \displaystyle \sum_{k=1}^{3} (v_{1k}\times w_{k1}) & \displaystyle \sum_{k=1}^{3} (v_{1k}\times w_{k2}) \\ 
   \displaystyle \sum_{k=1}^{3} (v_{2k}\times w_{k1}) & \displaystyle \sum_{k=1}^{3} (v_{2k}\times w_{k2})
  \end{matrix}
  \right]_{2x2}
$    

In [15]:
V = np.array( [[1,2,3],[4,5,6]] )
W = np.array( [[1,2],[3,4],[5,6]] )

# 矩陣相乘（內積）
D1 = np.dot( V, W )
D2 = V @ W

print( f'V = \n{V}\n' )
print( f'W = \n{W}\n' )
print( f'矩陣乘法 V．W = \n{D1}\n' )
print( f'矩陣乘法 V．W = \n{D2}' )

V = 
[[1 2 3]
 [4 5 6]]

W = 
[[1 2]
 [3 4]
 [5 6]]

矩陣乘法 V．W = 
[[22 28]
 [49 64]]

矩陣乘法 V．W = 
[[22 28]
 [49 64]]


# 數學函數

NumPy 也支援常見的數學函數，例如：`round( )`、`square( )`、`exp( )`、`sin( )`、`cos( )` 等，這些函數會分別作用於 NumPy 陣列中的每一個元素，最後回傳一個運算後的陣列。下列將介紹常用的數學函數：

## 四捨五入

In [16]:
X = np.array( [1.234, 5.678, 9.0] )

# 四捨五入到小數點以下第 2 位
R = np.round_( X, 2 )

# 小於或等於 X 的最大整數
F = np.floor( X )

# 大於或等於 X 的最小整數
C = np.ceil( X )

# 無條件捨去小數
T = np.trunc( X )

print( f'X = {X}\n' )
print( f'四捨五入到小數點以下第 2 位 = {R}' )
print( f'小於或等於 X 的最大整數 = {F}' )
print( f'大於或等於 X 的最小整數 = {C}' )
print( f'無條件捨去小數 = {T}' )

X = [1.234 5.678 9.   ]

四捨五入到小數點以下第 2 位 = [1.23 5.68 9.  ]
小於或等於 X 的最大整數 = [1. 5. 9.]
大於或等於 X 的最小整數 = [2. 6. 9.]
無條件捨去小數 = [1. 5. 9.]


## 指數\對數

In [17]:
X = np.array( [1,2,3] )

# 計算以 e 歐拉數(Euler's number)為底數、陣列元素為次方數的指數
E = np.exp( X )

# 計算以 2 為底數、陣列元素為次方數的指數
E2 = np.exp2( X )

# 取以 e 歐拉數(Euler's number)為底的對數
L = np.log( X )

# 取以 2 為底的對數
L2 = np.log2( X )

print( f'X = {X}\n' )
print( f'e^X = {E}' )
print( f'2^X = {E2}' )
print( f'log_e(X) = {L}' )
print( f'log_2(X) = {L2}' )

X = [1 2 3]

e^X = [ 2.71828183  7.3890561  20.08553692]
2^X = [2. 4. 8.]
log_e(X) = [0.         0.69314718 1.09861229]
log_2(X) = [0.        1.        1.5849625]


## 三角函數

In [18]:
X = np.array( [ 0, np.pi/2, np.pi, 3*np.pi/2 ] )

# 正弦值(sine)
S = np.sin( X )

# 餘弦值(cosine)
C = np.cos( X )

# 正切值(tangent)
T = np.tan( X )

# 雙曲正切值(hyperbolic tangent)
HT = np.tanh( X )

print( f'X = {X}\n' )
print( f'sin(X) = {S}' )
print( f'cos(X) = {C}' )
print( f'tan(X) = {T}' )
print( f'tanh(X) = {HT}' )

X = [0.         1.57079633 3.14159265 4.71238898]

sin(X) = [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
cos(X) = [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
tan(X) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]
tanh(X) = [0.         0.91715234 0.99627208 0.99983861]


# 結語   

在閱讀本文對 <font color="#00dd00">**NumPy**</font> 的基礎介紹後，我們已具有<font color="#00dd00">陣列( Array )</font>的基礎觀念，這將有助於我們後續學習資料處理及分析的另一個基礎套件 <font color="#00dd00">**Pandas**</font> ，實際上 ，Pandas 的資料儲存方法 <font color="#00dd00">DataFrame</font> 及 <font color="#00dd00">Series</font> 便是奠基於 NumPy 陣列之上。然而，當日後我們在進行資料分析時，免不了會遭遇到本文所沒有介紹的問題，建議讀者除可查詢 [Stack Overflow](https://stackoverflow.com/questions/tagged/python) 參考大神們的解法外，也可查詢官方文件 [NumPy Quickstart Tutorial](https://numpy.org/devdocs/user/quickstart.html) 尋找方法，以累積程式除錯的能力與經驗。   
針對本文的內容，若讀者們有發現任何的錯誤或疑問，非常歡迎您[來信( yenlinwu1112@gmail.com )](mailto:yenlinwu1112@gmail.com )給予建議及討論，讓我們一同來學習成長！

# [返回課程大綱](https://github.com/AI-FREE-Team/Machine-Learning-Basic)